Updated "Marketing Program," issue# 255
NoteHive/Silk-Corp-Guide pull request #258
Opened 2023-09-07 15:43 UTC by Aini-Bashir

I updated the source of image here.

2023-09-08 15:09 UTC, Alisha-Rashid approved these changes

2023-09-12 20:06 UTC, SuzyQuant approved these changes

2023-09-12 20:08 UTC, SuzyQuant requested changes
Use lower-case M since you changed it on the web page.

2023-09-13 11:09 UTC, Aini-Bashir commented
@SuzyQuant I'm doing changes from VS code insiders so I can also check the live preview. 
![image](https://github.com/NoteHive/Silk-Corp-Guide/assets/117284277/a84a8f77-faaa-405e-a5e2-d85a68d6b2e4)
On VS Code it's showing a small "m" and I also checked the live preview same is there.

2024-01-19 15:34 UTC, merged