Update image for entrepreneurship issue#261
NoteHive/Silk-Corp-Guide pull request #269
Opened 2023-09-12 17:44 UTC by Alisha-Rashid

I updated the image for issue#261 Entrepreneurship

2023-09-12 17:57 UTC, Aini-Bashir requested changes
Change the narration here as well.

2023-09-12 19:37 UTC, SuzyQuant approved these changes

2023-09-12 19:38 UTC, SuzyQuant approved these changes

2023-09-12 19:38 UTC, SuzyQuant approved these changes

2023-09-12 19:38 UTC, SuzyQuant approved these changes

2023-09-12 19:39 UTC, merged

2023-09-13 11:55 UTC, Aini-Bashir commented
Hey, @SuzyQuant I think we need to revert this because the image is not committed in the images folder and is not appearing on the website after being merged.

2023-09-20 11:03 UTC, Aini-Bashir commented
Hey @Alisha-Rashid, please redo this pull request.