Silk Home
NoteHive/Silk-Corp-Guide pull request #45
Opened 2023-04-21 17:24 UTC by Aiko-Kawamura

I updated Silk Home to website

2023-04-21 18:50 UTC, Remy-Reveltek requested changes
- Capitalize all letters of SILK
- Avoid using title inside description i.e. SILK Home

2023-04-24 10:55 UTC, Aiko-Kawamura commented
Done updating Silk Home.

2023-04-24 14:05 UTC, SuzyQuant approved these changes

2023-04-25 04:38 UTC, duafatimaa approved these changes

2023-04-29 19:21 UTC, merged