Updated Silk Yoga
NoteHive/Silk-Corp-Guide pull request #48
Opened 2023-04-24 11:10 UTC by Aiko-Kawamura

I updated text in Silk Yoga section on website.

2023-04-24 13:05 UTC, SuzyQuant reviewed
Edit second sentence.

2023-04-25 04:35 UTC, duafatimaa approved these changes

2023-04-25 12:32 UTC, Remy-Reveltek requested changes
You are putting dots in between (S.I.L.K), remove these. Otherwise content is looking good.

2023-04-25 12:37 UTC, Aiko-Kawamura commented
@Remy-Reveltek done removing dots.

2023-04-29 19:25 UTC, merged